/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMpesaStkRouteImport } from './routes/api/mpesa-stk'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa-callback'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaStkRoute = ApiMpesaStkRouteImport.update({
  id: '/api/mpesa-stk',
  path: '/api/mpesa-stk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa-callback',
  path: '/api/public/mpesa-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/products'
    | '/api/mpesa-stk'
    | '/api/public/mpesa-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/products'
    | '/api/mpesa-stk'
    | '/api/public/mpesa-callback'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/products'
    | '/api/mpesa-stk'
    | '/api/public/mpesa-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FaqRoute: typeof FaqRoute
  ProductsRoute: typeof ProductsRoute
  ApiMpesaStkRoute: typeof ApiMpesaStkRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa-stk': {
      id: '/api/mpesa-stk'
      path: '/api/mpesa-stk'
      fullPath: '/api/mpesa-stk'
      preLoaderRoute: typeof ApiMpesaStkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa-callback': {
      id: '/api/public/mpesa-callback'
      path: '/api/public/mpesa-callback'
      fullPath: '/api/public/mpesa-callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FaqRoute: FaqRoute,
  ProductsRoute: ProductsRoute,
  ApiMpesaStkRoute: ApiMpesaStkRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
